[0m22:20:17.244065 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4fa4862300>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4fa2a562d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4fa2a561b0>]}


============================== 22:20:17.248133 | e5e724ce-e0d4-4f4c-bcc9-32c4a3fdabb3 ==============================
[0m22:20:17.248133 [info ] [MainThread]: Running with dbt=1.9.2
[0m22:20:17.248825 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/fede/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt build', 'send_anonymous_usage_stats': 'True'}
[0m22:20:17.249409 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/fede/mlops/dagster/user-code-dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:20:17.250508 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.12411577, "process_in_blocks": "488", "process_kernel_time": 0.263572, "process_mem_max_rss": "89788", "process_out_blocks": "8", "process_user_time": 1.964768}
[0m22:20:17.251077 [debug] [MainThread]: Command `dbt build` failed at 22:20:17.250958 after 0.12 seconds
[0m22:20:17.251605 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4fa2a56600>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4fa2a56180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4fa2a56720>]}
[0m22:20:17.252093 [debug] [MainThread]: Flushing usage events
[0m22:20:17.947373 [debug] [MainThread]: An error was encountered while trying to flush usage events
